package com.deal.base.pojo;
// Generated Mar 23, 2018 7:09:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Admins generated by hbm2java
 */
@Entity
@Table(name="ADMINS"
    ,schema="DEALTIME"
    , uniqueConstraints = {@UniqueConstraint(columnNames="PHONE_NUMBER"), @UniqueConstraint(columnNames="EMAIL")} 
)
public class Admins  implements java.io.Serializable {


     private BigDecimal adminId;
     private String email;
     private String password;
     private String firstName;
     private String lastName;
     private String address;
     private String job;
     private String phoneNumber;
     private Date dateOfBirth;

    public Admins() {
    }

	
    public Admins(BigDecimal adminId, String email, String password, String firstName, String lastName, String phoneNumber) {
        this.adminId = adminId;
        this.email = email;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNumber = phoneNumber;
    }
    public Admins(BigDecimal adminId, String email, String password, String firstName, String lastName, String address, String job, String phoneNumber, Date dateOfBirth) {
       this.adminId = adminId;
       this.email = email;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.job = job;
       this.phoneNumber = phoneNumber;
       this.dateOfBirth = dateOfBirth;
    }
   
     @Id 

    
    @Column(name="ADMIN_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(BigDecimal adminId) {
        this.adminId = adminId;
    }

    
    @Column(name="EMAIL", unique=true, nullable=false, length=200)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="PASSWORD", nullable=false, length=60)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="FIRST_NAME", nullable=false, length=60)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LAST_NAME", nullable=false, length=60)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="ADDRESS", length=300)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="JOB", length=120)
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }

    
    @Column(name="PHONE_NUMBER", unique=true, nullable=false, length=60)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_OF_BIRTH", length=7)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }




}


