package com.deal.base.pojo;
// Generated Mar 23, 2018 7:09:10 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "CATEGORIES",
         schema = "DEALTIME",
         uniqueConstraints = @UniqueConstraint(columnNames = "CATEGORY_NAME")
)
public class Category implements java.io.Serializable {

    private BigDecimal categoryId;
    private String categoryName;

    public Category() {
    }

    public Category(BigDecimal categoryId, String categoryName) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
    }
    public Category( String categoryName) {
        this.categoryName = categoryName;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "my_CATEGORIES_SEQ_gen")
    @SequenceGenerator(name = "my_CATEGORIES_SEQ_gen", sequenceName = "CATEGORIES_SEQ")

    @Column(name = "CATEGORY_ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(BigDecimal categoryId) {
        this.categoryId = categoryId;
    }

    @Column(name = "CATEGORY_NAME", unique = true, nullable = false, length = 200)
    public String getCategoryName() {
        return this.categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

}
