package com.deal.base.pojo;
// Generated Mar 23, 2018 7:09:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="CUSTOMERS"
    ,schema="DEALTIME"
    , uniqueConstraints = {@UniqueConstraint(columnNames="PHONE_NUMBER"), @UniqueConstraint(columnNames="EMAIL")} 
)
public class Customer  implements java.io.Serializable {


     private BigDecimal custId;
     private String email;
     private String password;
     private String firstName;
     private String lastName;
     private String address;
     private String job;
     private String phoneNumber;
     private Date dateOfBirth;
     private BigDecimal creditLimit;
     private String wishlist;
//     private Set<Order> orderses = new HashSet<Order>(0);

    public Customer() {
    }

	
    public Customer(BigDecimal custId, String email, String password, String firstName, String lastName, String phoneNumber, BigDecimal creditLimit) {
        this.custId = custId;
        this.email = email;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNumber = phoneNumber;
        this.creditLimit = creditLimit;
    }
//    public Customer(BigDecimal custId, String email, String password, String firstName, String lastName, String address, String job, String phoneNumber, Date dateOfBirth, BigDecimal creditLimit, String wishlist, Set<Order> orderses) {
//       this.custId = custId;
//       this.email = email;
//       this.password = password;
//       this.firstName = firstName;
//       this.lastName = lastName;
//       this.address = address;
//       this.job = job;
//       this.phoneNumber = phoneNumber;
//       this.dateOfBirth = dateOfBirth;
//       this.creditLimit = creditLimit;
//       this.wishlist = wishlist;
//       this.orderses = orderses;
//    }
   

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "my_CUSTOMERS_SEQ_gen")
    @SequenceGenerator(name = "my_CUSTOMERS_SEQ_gen", sequenceName = "CUSTOMERS_SEQ")

    
    @Column(name="CUSTOMER_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCustId() {
        return this.custId;
    }
    
    public void setCustId(BigDecimal customerId) {
        this.custId = customerId;
    }

    
    @Column(name="EMAIL", unique=true, nullable=false, length=200)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="PASSWORD", nullable=false, length=60)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="FIRST_NAME", nullable=false, length=60)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LAST_NAME", nullable=false, length=200)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="ADDRESS", length=300)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="JOB", length=120)
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }

    
    @Column(name="PHONE_NUMBER", unique=true, nullable=false, length=60)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_OF_BIRTH", length=7)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    
    @Column(name="CREDIT_LIMIT", nullable=false, precision=22, scale=0)
    public BigDecimal getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(BigDecimal creditLimit) {
        this.creditLimit = creditLimit;
    }

    
    @Column(name="WISHLIST", length=400)
    public String getWishlist() {
        return this.wishlist;
    }
    
    public void setWishlist(String wishlist) {
        this.wishlist = wishlist;
    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="customers")
//    public Set<Order> getOrderses() {
//        return this.orderses;
//    }
//    
//    public void setOrderses(Set<Order> orderses) {
//        this.orderses = orderses;
//    }




}


