package com.deal.base.pojo;
// Generated Mar 23, 2018 7:09:10 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "ORDERS",
        schema = "DEALTIME"
)
public class Order implements java.io.Serializable {

    private BigDecimal orderId;
    private Customer customer;
    private Product orderProduct;
    private BigDecimal quantity;
    private String status;

    public Order() {
    }

    public Order(BigDecimal orderId, Customer customers, Product products) {
        this.orderId = orderId;
        this.customer = customers;
        this.orderProduct = products;
    }

    public Order(BigDecimal orderId, Customer customers, Product products, BigDecimal quantity, String status) {
        this.orderId = orderId;
        this.customer = customers;
        this.orderProduct = products;
        this.quantity = quantity;
        this.status = status;
    }
    public Order( Customer customers, Product products, BigDecimal quantity, String status) {
        this.orderId = orderId;
        this.customer = customers;
        this.orderProduct = products;
        this.quantity = quantity;
        this.status = status;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "my_ORDERS_SEQ_gen")
    @SequenceGenerator(name = "my_ORDERS_SEQ_gen", sequenceName = "ORDERS_SEQ")
    @Column(name = "ORDER_ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getOrderId() {
        return this.orderId;
    }

    public void setOrderId(BigDecimal orderId) {
        this.orderId = orderId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CUSTOMER_ID", nullable = false)
    public Customer getCustomer() {
        return this.customer;
    }

    public void setCustomer(Customer customers) {
        this.customer = customers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PRODUCT_ID", nullable = false)
    public Product getOrderProduct() {
        return this.orderProduct;
    }

    public void setOrderProduct(Product products) {
        this.orderProduct = products;
    }

    @Column(name = "QUANTITY", precision = 22, scale = 0)
    public BigDecimal getQuantity() {
        return this.quantity;
    }

    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    @Column(name = "STATUS", length = 1)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
