package com.deal.base.pojo;
// Generated Mar 23, 2018 7:09:10 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "PRODUCTS",
        schema = "DEALTIME",
        uniqueConstraints = @UniqueConstraint(columnNames = "PRODUCT_NAME")
)
public class Product implements java.io.Serializable {

    private BigDecimal productId;
    private String productName;
    private String productDescription;
    private BigDecimal productPrice;
    private BigDecimal availableQuantity;
    private Category productCategory;
    private String imageFilename;
//     private Set<Order> orderses = new HashSet<Order>(0);

    public Product() {
    }

    public Product(BigDecimal productId, String productName) {
        this.productId = productId;
        this.productName = productName;
    }

    public Product(BigDecimal productId, String productName, String productDescription, BigDecimal price, BigDecimal availableQuantity, Category categoryId, String imageFilename) {
        this.productId = productId;
        this.productName = productName;
        this.productDescription = productDescription;
        this.productPrice = price;
        this.availableQuantity = availableQuantity;
        this.productCategory = categoryId;
        this.imageFilename = imageFilename;
    }

    public Product(String productName, String productDescription, BigDecimal price, BigDecimal availableQuantity, Category categoryId, String imageFilename) {
        this.productName = productName;
        this.productDescription = productDescription;
        this.productPrice = price;
        this.availableQuantity = availableQuantity;
        this.productCategory = categoryId;
        this.imageFilename = imageFilename;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "my_PRODUCTS_SEQ_gen")
    @SequenceGenerator(name = "my_PRODUCTS_SEQ_gen", sequenceName = "PRODUCTS_SEQ")

    @Column(name = "PRODUCT_ID", unique = true, nullable = false)
    public BigDecimal getProductId() {
        return this.productId;
    }

    public void setProductId(BigDecimal productId) {
        this.productId = productId;
    }

    @Column(name = "PRODUCT_NAME", unique = true, nullable = false, length = 200)
    public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    @Column(name = "PRODUCT_DESCRIPTION", length = 600)
    public String getProductDescription() {
        return this.productDescription;
    }

    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    @Column(name = "PRICE", precision = 22, scale = 0)
    public BigDecimal getProductPrice() {
        return this.productPrice;
    }

    public void setProductPrice(BigDecimal price) {
        this.productPrice = price;
    }

    @Column(name = "AVAILABLE_QUANTITY", precision = 22, scale = 0)
    public BigDecimal getAvailableQuantity() {
        return this.availableQuantity;
    }

    public void setAvailableQuantity(BigDecimal availableQuantity) {
        this.availableQuantity = availableQuantity;
    }

    // modified as CATEGORY_ID is not just an integer it is a relation
//    @Column(name="CATEGORY_ID", precision=22, scale=0)
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_Id", nullable = true)
    public Category getProductCategory() {
        return this.productCategory;
    }

    public void setProductCategory(Category categoryId) {
        this.productCategory = categoryId;
    }

    @Column(name = "IMAGE_FILENAME", length = 200)
    public String getImageFilename() {
        return this.imageFilename;
    }

    public void setImageFilename(String imageFilename) {
        this.imageFilename = imageFilename;
    }

// commented as we will never need to get orders form product  
//@OneToMany(fetch=FetchType.LAZY, mappedBy="products")
//    public Set<Order> getOrderses() {
//        return this.orderses;
//    }
//    
//    public void setOrderses(Set<Order> orderses) {
//        this.orderses = orderses;
//    }
    @Override
    public String toString() {
        return "Product{" + "productId=" + productId + ", productName=" + productName + ", productPrice=" + productPrice + ", availableQuantity=" + availableQuantity + ", productCategory=" + productCategory + '}';
    }

}
